### PR TITLE
Remove all turtlebot related launch files

### PR DESCRIPTION
**Pull request by ahtsan**
This repository should be a pure world repository and not having any navigation related code.

* Remove all navigation launch files
* Remove all navigation dependencies

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cheng-kevin** [comment]
Are these mapping files in **aws-robomaker-bookstore-world/maps/turtlebot3_waffle_pi/** specific to waffle_pi or could they be renamed?

**Comment by ahtsan** [comment]
> Are these mapping files in **aws-robomaker-bookstore-world/maps/turtlebot3_waffle_pi/** specific to waffle_pi or could they be renamed?

I think they were generated specifically with waffle_pi, so they can't be renamed. Need to check with @mm318 @samuelgundry

**Comment by cheng-kevin** [comment]
> > Are these mapping files in **aws-robomaker-bookstore-world/maps/turtlebot3_waffle_pi/** specific to waffle_pi or could they be renamed?
> 
> I think they were generated specifically with waffle_pi, so they can't be renamed. Need to check with @mm318 @samuelgundry

Got it.  I guess these mappings files would be the last turtlebot3 specific remnants, and do we think this would affect our definition of "pure world repository".

**Comment by ahtsan** [comment]
> > > Are these mapping files in **aws-robomaker-bookstore-world/maps/turtlebot3_waffle_pi/** specific to waffle_pi or could they be renamed?
> > 
> > 
> > I think they were generated specifically with waffle_pi, so they can't be renamed. Need to check with @mm318 @samuelgundry
> 
> Got it. I guess these mappings files would be the last turtlebot3 specific remnants, and do we think this would affect our definition of "pure world repository".

Good point. It would be ideal to exclude the map files but it is out of this PR's scope. Now we are "navigation-free" but not "turtlebot3-free".

**Review by cheng-kevin — APPROVED** [review]

**Comment by mm318** [comment]
Yeah, the goal here is to make the `ros1` branch consistent with the `ros2` branch.

There is unfortunately no clear home for where the Turtlebot-specific occupancy maps should reside, so let's just leave it in the sample world repos for now.

**Review by mm318 — APPROVED** [review]

**Comment by mm318** [comment]
This change needs to go in atomically with https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/137.

**Pull request merged**
