### PR TITLE
Add param yaml files for navigation

### PR DESCRIPTION
**Pull request by ahtsan**
*Issue #, if available:*
Param files are missing in this repo, which are required by cloudwatch sample app ROS2 navigation.

*Description of changes:*
Add the missing param files

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ojasjoshi** [comment]
where were these params coming from originally?

**Comment by ahtsan** [comment]
> where were these params coming from originally?

https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/tree/ros2/simulation_ws/src/cloudwatch_simulation/param

**Comment by ahtsan** [comment]
Basically both the map and param files were living inside cloudwatch sample app, and they are both specific for bookstore

**Comment by mm318** [comment]
> > where were these params coming from originally?
> 
> https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/tree/ros2/simulation_ws/src/cloudwatch_simulation/param

So we should remove them later?

**Review by mm318 — APPROVED** [review]

**Review by ojasjoshi — APPROVED** [review]

**Comment by ahtsan** [comment]
> > > where were these params coming from originally?
> > 
> > 
> > https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/tree/ros2/simulation_ws/src/cloudwatch_simulation/param
> 
> So we should remove them later?

Yes, I removed them in this [PR](https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/143)

**Pull request merged**
